import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/footer";
import Nav from "./components/nav";
import { satoshi, brule } from "./fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${brule.variable} font-satoshi antialiased`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
